NAVQP-151: update to 6.1.22 NXP baseline
voxelbotics/meta-vb-imx8mp pull request #80
Opened 2023-09-15 13:30 UTC by db-voxel

2023-09-17 21:38 UTC, avyurtsev approved these changes, later dismissed

2023-09-17 22:08 UTC, avyurtsev commented on scripts/build6-1-22.sh
Line 71 needs editing:
```
- repo init -u https://github.com/nxp-imx/imx-manifest.git -b imx-linux-kirkstone -m ${MANIFEST} || exit $?
+ repo init -u https://github.com/nxp-imx/imx-manifest.git -b imx-linux-mickledore -m ${MANIFEST} || exit $?
```

2023-09-17 22:09 UTC, avyurtsev requested changes
Line 71 needs editing:
```
- repo init -u https://github.com/nxp-imx/imx-manifest.git -b imx-linux-kirkstone -m ${MANIFEST} || exit $?
+ repo init -u https://github.com/nxp-imx/imx-manifest.git -b imx-linux-mickledore -m ${MANIFEST} || exit $?
```

2023-09-18 05:42 UTC, db-voxel commented
> Line 71 in build6-1-22.sh needs editing :
> 
> ```
> - repo init -u https://github.com/nxp-imx/imx-manifest.git -b imx-linux-kirkstone -m ${MANIFEST} || exit $?
> + repo init -u https://github.com/nxp-imx/imx-manifest.git -b imx-linux-mickledore -m ${MANIFEST} || exit $?
> ```

Addressed.

2023-09-18 08:33 UTC, avyurtsev approved these changes

2023-09-18 08:34 UTC, merged